### ISSUE TITLE
Add channel and code for segmentation

### ISSUE THREAD

**Issue by perp** [DylanWusee/pointconv_pytorch#1]
How to add other channel for classification? intensity or RGB eg.
When will code for segmentation release?
Thanks a lot

**Comment by AruniRC** [comment]
Just a bump on this issue -- it would be great to have a part segmentation codebase available in PyTorch!

**Comment by DylanWusee** [comment]
Will do in future.

**Comment by THHHomas** [comment]
Hope the part segmentation code will be available.

**Comment by P-Light** [comment]
Still waiting 🤞
