### ISSUE TITLE
Run eval_cls_conv.py code

### ISSUE THREAD

**Issue by bimsarapathiraja** [DylanWusee/pointconv_pytorch#2]
I was able to run train_cls_conv.py code. Then how can I evaluate using eval_cls_conv.py code. I am confused with the part "path/to/checkpoint" part

Is that the eval_experiment folder or experiment folder?

**Comment by zx19950617** [comment]
Hi, @bimsarapathiraja! have you achieved the classification accuracy (92.5%) shown in the paper? Why did I get the only 0.91456 accuracy using the Adam optimizer? 
![2019-12-16 15-45-33屏幕截图](https://user-images.githubusercontent.com/38937499/70888471-5c1f9180-201b-11ea-95a6-fa2cbca6c201.png)
