### ISSUE TITLE
Decoder part in pointconv

### ISSUE THREAD

**Issue by Ophelia20444** [DylanWusee/pointconv_pytorch#3]
When will code for segmentation release? 
Especially the part of Encoder-Decoder?
Thanks and looking forward your answer.

**Comment by DylanWusee** [comment]
Sorry that I couldn't give you an exact date. But, we will do that ASAP.

**Comment by ooodragon94** [comment]
is it up now??

**Comment by Ophelia20444** [comment]
Apparently, No.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DylanWusee/pointconv_pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月8日(星期五) 下午2:45
收件人:&nbsp;"DylanWusee/pointconv_pytorch"<pointconv_pytorch@noreply.github.com&gt;;
抄送:&nbsp;"蝴蝶骨"<shanshan_han@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DylanWusee/pointconv_pytorch] Decoder part in pointconv (#3)





 
is it up now??

**Comment by ooodragon94** [comment]
hope it comes soon :cry:
