### ISSUE TITLE
change the number of points of input

### ISSUE THREAD

**Issue by wtpro** [DylanWusee/pointconv_pytorch#5]
Thanks for your amazing work on the network!
Is there a way to change the input size? I want to do training on a dataset with 10000 points in each point cloud. I have checked you paper but there is no structure regarding the classification network.

**Comment by GYE19970220** [comment]
> Thanks for your amazing work on the network!
> Is there a way to change the input size? I want to do training on a dataset with 10000 points in each point cloud. I have checked you paper but there is no structure regarding the classification network.

Excuse me,How to modify the number of input points?

**Comment by DylanWusee** [comment]
you can use the arguments "num_point" to set the number of points.
